<?php

/**
 * @file
 * Lists available colors and color schemes for the Convivial BS5 theme.
 */

$info = [
  // Available colors and color labels used in theme.
  'fields' => [
    'standard_light' => t('Standard light color'),
    'standard_dark' => t('Standard dark color'),
    'standard_link' => t('Standard link color'),
    'standard_focus' => t('Standard focus color'),
    'standard_accent' => t('Standard accent color'),
    'light_bg' => t('Light background'),
    'light_link' => t('Light link'),
    'light_accent' => t('Light accent'),
    'light_focus' => t('Light focus'),
    'dark_bg' => t('Dark background'),
    'dark_link' => t('Dark link'),
    'dark_accent' => t('Dark accent'),
    'dark_focus' => t('Dark focus'),
    'primary_light_bg' => t('Primary light background'),
    'primary_light_link' => t('Primary light link'),
    'primary_light_accent' => t('Primary light accent'),
    'primary_light_focus' => t('Primary light focus'),
    'primary_dark_bg' => t('Primary dark background'),
    'primary_dark_link' => t('Primary dark link'),
    'primary_dark_accent' => t('Primary dark accent'),
    'primary_dark_focus' => t('Primary dark focus'),
  ],

  // Pre_defined color schemes.
  'schemes' => [
    'default' => [
      'title' => t('Default'),
      'colors' => [
        'standard_light' => '#FFFFFF',
        'standard_dark' => '#000000',
        'standard_link' => '#066DAC',
        'standard_accent' => '#064771',
        'standard_focus' => '#9506BC',
        'light_bg' => '#F0F0F0',
        'light_link' => '#066DAC',
        'light_accent' => '#064771',
        'light_focus' => '#8806AC',
        'dark_bg' => '#064771',
        'dark_link' => '#68BEF8',
        'dark_accent' => '#9FD5F9',
        'dark_focus' => '#DBA4F9',
        'primary_light_bg' => '#D9EEFC',
        'primary_light_link' => '#07609C',
        'primary_light_accent' => '#064771',
        'primary_light_focus' => '#83079C',
        'primary_dark_bg' => '#066DAC',
        'primary_dark_link' => '#FBFCFE',
        'primary_dark_accent' => '#FBFCFE',
        'primary_dark_focus' => '#FCF7FD',
      ],
    ],
  ],
];
